configs:
- name: maxep100_lr1e-04_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-04_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-04_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-04_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-03_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-03_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-03_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-03_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-02_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-02_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-02_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep100_lr1e-02_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 100
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-04_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-04_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-04_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-04_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-03_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-03_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-03_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-03_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-02_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-02_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-02_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep1000_lr1e-02_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 1000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-04_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-04_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-04_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-04_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-03_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-03_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-03_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-03_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-02_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-02_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-02_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep3000_lr1e-02_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 3000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-04_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-04_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-04_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-04_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.0001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-03_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-03_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-03_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-03_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.001
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-02_w1e-03
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.001
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-02_w1e-02
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.01
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-02_w1e-01
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 0.1
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
- name: maxep5000_lr1e-02_w1e+00
  N_INITIAL: 100
  N_BOUNDARY: 100
  N_REGION: 5000
  MAX_EPOCHS_FOR_MODEL: 5000
  MAX_EPOCHS_FOR_FITTING: 1000
  LEARNING_RATE: 0.01
  PI_WEIGHT: 1.0
  VELOCITY: 1
  EPOCH_SEPARATOR: 10
